version: '3'
services:
  browserless:
    image: browserless/chrome
    environment:
      MAX_CONCURRENT_SESSIONS: 5
      MAX_QUEUE_LENGTH: 5
      CONNECTION_TIMEOUT: -1
    ports:
      - 33000:3000
  api:
    build: .
    environment:
      BROWSERLESS_URL: ws://browserless:3000/?stealth
    ports:
      - 9000:9000